services:
  - type: web
    name: assassin-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn assassin_api_complete:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
